Repository skroutz/mistry, pull requests merged in 2018-04, with the labels that each got.

#17 Add a Web view
  .gitignore
  .travis.yml
  Makefile
  README.md
  cmd/mistryd/Gopkg.lock
  cmd/mistryd/Gopkg.toml
  cmd/mistryd/job.go
  cmd/mistryd/main.go
  cmd/mistryd/public/css/foundation.min.css
  cmd/mistryd/public/index.html
  cmd/mistryd/public/js/index.js
  cmd/mistryd/public/templates/show.html
  cmd/mistryd/server.go
  cmd/mistryd/server_test.go
  cmd/mistryd/worker.go
  pkg/broker/broker.go
  pkg/tailer/tailer.go
  pkg/types/build_result.go
Labels: feature

#46 Fix logic to determine job directory bootstraping
  cmd/mistryd/end_to_end_test.go
  cmd/mistryd/job.go
  cmd/mistryd/testdata/projects/bootstrap-twice/Dockerfile
  cmd/mistryd/testdata/projects/bootstrap-twice/docker-entrypoint.sh
  cmd/mistryd/worker.go
Labels: bug, server

#55 Add purger script for removing stale jobs
  contrib/mistry-purge-builds
Labels: enhancement

#57 only cleanup the pending dir if it wasnt successfully copied to ready
  cmd/mistryd/worker.go
Labels: bug
